
try {

    # Set the path to the folder containing the shortcut files
    $folderPath = "$PSScriptRoot\shortcuts"

    # Shortcuts generated by PowerToys Workspaces
    $shortcuts = Get-ChildItem -Path $folderPath -Filter *.lnk
    $desktopToEndAt = ""
    $shortcutToEndAt
 
    # Create a new SpVoice objects
    $voice = New-Object -ComObject Sapi.spvoice

    # Set the speed - positive numbers are faster, negative numbers, slower
    $voice.rate = 0

    $i = 0
    foreach ($shortcut in $shortcuts) {

        $shortcutName = "$($shortcut.BaseName)"
        if ($shortcutName -like "*Primary*") {
            $desktopToEndAt = $shortcutName
            $shortcutToEndAt = $shortcut
            continue
        }
        Write-Host "Switching to $shortcutName"
        Switch-Desktop $shortcutName
        Invoke-Item $shortcut
        Start-Sleep 20
        ++$i
    }

    if ($desktopToEndAt -ne "") {
        Write-Host "Switching to $desktopToEndAt"
        Switch-Desktop $desktopToEndAt
        Invoke-Item $shortcutToEndAt
        Start-Sleep 20
        
        $wavPath = Join-Path -Path $PSScriptRoot -ChildPath 'tetoHiSystemReady.wav'

        $player = New-Object System.Media.SoundPlayer
        $player.SoundLocation = $wavPath
        $player.Load()          # Preload to catch errors early
        $player.PlaySync()      # Blocks until the sound is done
    
    }



}
catch {
    Write-Host $_.Exception.Message
    $voice.speak("Error!")
    Read-Host
}
